export const statesData = [
  { label: 'Abia', value: 'Abia' },
  { label: 'Adamawa', value: 'Adamawa' },
  { label: 'Akwa Ibom', value: 'Akwa Ibom' },
  { label: 'Anambra', value: 'Anambra' },
  { label: 'Bauchi', value: 'Bauchi' },
  { label: 'Bayelsa', value: 'Bayelsa' },
  { label: 'Benue', value: 'Benue' },
  { label: 'Borno', value: 'Borno' },
  { label: 'Cross River', value: 'Cross River' },
  { label: 'Delta', value: 'Delta' },
  { label: 'Ebonyi', value: 'Ebonyi' },
  { label: 'Edo', value: 'Edo' },
  { label: 'Ekiti', value: 'Ekiti' },
  { label: 'Enugu', value: 'Enugu' },
  { label: 'Gombe', value: 'Gombe' },
  { label: 'Imo', value: 'Imo' },
  { label: 'Jigawa', value: 'Jigawa' },
  { label: 'Kaduna', value: 'Kaduna' },
  { label: 'Kano', value: 'Kano' },
  { label: 'Katsina', value: 'Katsina' },
  { label: 'Kebbi', value: 'Kebbi' },
  { label: 'Kogi', value: 'Kogi' },
  { label: 'Kwara', value: 'Kwara' },
  { label: 'Lagos', value: 'Lagos' },
  { label: 'Nasarawa', value: 'Nasarawa' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Ogun', value: 'Ogun' },
  { label: 'Ondo', value: 'Ondo' },
  { label: 'Osun', value: 'Osun' },
  { label: 'Oyo', value: 'Oyo' },
  { label: 'Plateau', value: 'Plateau' },
  { label: 'Rivers', value: 'Rivers' },
  { label: 'Sokoto', value: 'Sokoto' },
  { label: 'Taraba', value: 'Taraba' },
  { label: 'Yobe', value: 'Yobe' },
  { label: 'Zamfara', value: 'Zamfara' },
  { label: 'FCT - Abuja', value: 'FCT - Abuja' },
];

export const localGovtAreasData = [
  { label: 'Ajingi', value: 'Ajingi' },
  { label: 'Albasu', value: 'Albasu' },
  { label: 'Bagwai', value: 'Bagwai' },
  { label: 'Bebeji', value: 'Bebeji' },
  { label: 'Bichi', value: 'Bichi' },
  { label: 'Bunkure', value: 'Bunkure' },
  { label: 'Dala', value: 'Dala' },
  { label: 'Dambatta', value: 'Dambatta' },
  { label: 'Dawakin Kudu', value: 'Dawakin Kudu' },
  { label: 'Dawakin Tofa', value: 'Dawakin Tofa' },
  { label: 'Doguwa', value: 'Doguwa' },
  { label: 'Fagge', value: 'Fagge' },
  { label: 'Gabasawa', value: 'Gabasawa' },
  { label: 'Garko', value: 'Garko' },
  { label: 'Garun Mallam', value: 'Garun Mallam' },
  { label: 'Gaya', value: 'Gaya' },
  { label: 'Gezawa', value: 'Gezawa' },
  { label: 'Gwale', value: 'Gwale' },
  { label: 'Gwarzo', value: 'Gwarzo' },
  { label: 'Kabo', value: 'Kabo' },
  { label: 'Kano Municipal', value: 'Kano Municipal' },
  { label: 'Karaye', value: 'Karaye' },
  { label: 'Kibiya', value: 'Kibiya' },
  { label: 'Kiru', value: 'Kiru' },
  { label: 'Kumbotso', value: 'Kumbotso' },
  { label: 'Kunchi', value: 'Kunchi' },
  { label: 'Kura', value: 'Kura' },
  { label: 'Madobi', value: 'Madobi' },
  { label: 'Makoda', value: 'Makoda' },
  { label: 'Minjibir', value: 'Minjibir' },
  { label: 'Nasarawa', value: 'Nasarawa' },
  { label: 'Rano', value: 'Rano' },
  { label: 'Rimin Gado', value: 'Rimin Gado' },
  { label: 'Rogo', value: 'Rogo' },
  { label: 'Shanono', value: 'Shanono' },
  { label: 'Sumaila', value: 'Sumaila' },
  { label: 'Takai', value: 'Takai' },
  { label: 'Tarauni', value: 'Tarauni' },
  { label: 'Tofa', value: 'Tofa' },
  { label: 'Tsanyawa', value: 'Tsanyawa' },
  { label: 'Tudun Wada', value: 'Tudun Wada' },
  { label: 'Ungogo', value: 'Ungogo' },
  { label: 'Warawa', value: 'Warawa' },
  { label: 'Wudil', value: 'Wudil' },
];

export const genderData = [
  { label: 'Male', value: 'Male' },
  { label: 'Female', value: 'Female' },
  { label: 'Other', value: 'Other' },
];

export const govtIdData = [
  {
    label: 'NIN',
    value: 'Nin',
  },
  { label: 'Voter Card', value: 'Voter' },
  { label: 'Driver License', value: 'DL' },
  { label: 'Intrenational Passport', value: 'IP' },
];

export const transactionsList = [
  {
    id: '1',
    direction: 'out',
    token: 'ETH',
    amount: '-1',
    fiatValue: '1585.43',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '2',
    direction: 'out',
    token: 'USDT',
    amount: '-1',
    fiatValue: '1.00',
    status: 'failed',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '3',
    direction: 'out',
    token: 'BNB',
    amount: '-1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '4',
    direction: 'in',
    token: 'ETH',
    amount: '+1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '5',
    direction: 'out',
    token: 'USDT',
    amount: '-1',
    fiatValue: '1.00',
    status: 'failed',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '6',
    direction: 'in',
    token: 'ETH',
    amount: '+1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '7',
    direction: 'in',
    token: 'BNB',
    amount: '+1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '8',
    direction: 'in',
    token: 'BNB',
    amount: '+1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
  {
    id: '9',
    direction: 'in',
    token: 'ETH',
    amount: '+1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: '0xed959Fb...F725B9',
  },
];

export const mobileTransactionsList = [
  {
    id: '1',
    direction: 'out',
    amount: '1',
    fiatValue: '1585.43',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '2',
    direction: 'out',
    amount: '1',
    fiatValue: '1.00',
    status: 'failed',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '3',
    direction: 'out',
    amount: '1',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '4',
    direction: 'in',
    amount: '300',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '5',
    direction: 'out',
    amount: '1',
    fiatValue: '1.00',
    status: 'failed',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '6',
    direction: 'in',
    amount: '300',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '7',
    direction: 'in',
    amount: '300',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '8',
    direction: 'in',
    amount: '300',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
  {
    id: '9',
    direction: 'in',
    amount: '300',
    fiatValue: '1.00',
    status: 'success',
    date: '11 May 2025',
    address: 'Ikenna Babalola',
  },
];

export const notifications = [
  {
    id: '1',
    title: 'Amount Received',
    message: '₦500 received from John Doe. Credited to your wallet.',
    date: '10:47 AM',
  },
  {
    id: '2',
    title: 'Amount Sent',
    message: '₦500 sent to Mazumi. Debited from your wallet successfully.',
    date: '09:15 AM',
  },
  {
    id: '3',
    title: 'Cashback Reward',
    message: "You've received a ₦1000 gift card as a cashback reward!",
    date: '08:30 PM',
  },
  {
    id: '4',
    title: 'Login Alert',
    message: 'New login detected from a new device at 07:12 PM.',
    date: '07:15 PM',
  },
  {
    id: '5',
    title: 'Payment Successful',
    message: 'Payment of ₦1,200 to ZedGroceries completed successfully.',
    date: '11:45 AM',
  },
  {
    id: '6',
    title: 'Offer Unlocked',
    message: 'You just unlocked a 10% discount on your next purchase!',
    date: '09:00 AM',
  },
  {
    id: '7',
    title: 'Referral Bonus',
    message: '₦250 credited to your wallet for referring Emmanuel.',
    date: '03:42 PM',
  },
  {
    id: '8',
    title: 'KYC Verified',
    message: 'Congratulations! Your KYC has been verified successfully.',
    date: '01:25 PM',
  },
  {
    id: '9',
    title: 'Security Update',
    message: 'Your password was changed successfully.',
    date: '05:10 PM',
  },
  {
    id: '10',
    title: 'Monthly Statement',
    message: 'Your wallet statement for June is now available to download.',
    date: '08:00 AM',
  },
];
